namespace Xcalibur.HardwareMonitor.Framework.Hardware.Motherboard;

internal class Voltage
{
    /// <summary>
    /// Gets the index.
    /// </summary>
    /// <value>
    /// The index.
    /// </value>
    public int Index { get; }

    /// <summary>
    /// Gets the name.
    /// </summary>
    /// <value>
    /// The name.
    /// </value>
    public string Name { get; }

    /// <summary>
    /// The voltage, or electric potential difference between two points, determines the strength of the
    /// RF signal generated by the generator. RF voltage standards are used to calibrate instruments like
    /// RF millivoltmeters, oscilloscopes, and EMC receivers.
    /// </summary>
    /// <value>
    /// The rf.
    /// </value>
    public float Rf { get; }

    /// <summary>
    /// The input resistor and the source resistance are in series, and their sum determines the voltage gain.
    /// In practice, it's usually best to include a separate resistor as the input resistor, as the source
    /// resistance is often an estimate.
    /// </summary>
    /// <value>
    /// The ri.
    /// </value>
    public float Ri { get; }

    /// <summary>
    /// The forward voltage is the amount of voltage needed to get current to flow across a diode.
    /// This is important to know because if you are trying to get a signal through a diode that is
    /// less than the forward voltage, you will be disappointed.
    /// </summary>
    /// <value>
    /// The vf.
    /// </value>
    public float Vf { get; }

    /// <summary>
    /// Gets a value indicating whether this <see cref="Voltage"/> is hidden.
    /// </summary>
    /// <value>
    ///   <c>true</c> if hidden; otherwise, <c>false</c>.
    /// </value>
    public bool IsHidden { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Voltage"/> class.
    /// </summary>
    /// <param name="name">The name.</param>
    /// <param name="index">The index.</param>
    /// <param name="hidden">if set to <c>true</c> [hidden].</param>
    public Voltage(string name, int index, bool hidden = false) : this(name, index, 0, 1, 0, hidden) { }

    /// <summary>
    /// Initializes a new instance of the <see cref="Voltage"/> class.
    /// </summary>
    /// <param name="name">The name.</param>
    /// <param name="index">The index.</param>
    /// <param name="ri">The ri.</param>
    /// <param name="rf">The rf.</param>
    /// <param name="vf">The vf.</param>
    /// <param name="hidden">if set to <c>true</c> [hidden].</param>
    public Voltage(string name, int index, float ri, float rf, float vf = 0, bool hidden = false)
    {
        Name = name;
        Index = index;
        Ri = ri;
        Rf = rf;
        Vf = vf;
        IsHidden = hidden;
    }
}